import '../styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ThemeChanger from '@/app/components/ThemeChanger';
import ThemeProvider from '@/app/components/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider>
          <ThemeChanger />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
