import '../styles/globals.css';

import clsx from 'clsx';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

import Header from '@/app/components/Header';
import ThemeProvider from '@/app/components/ThemeProvider';

const GmarketSans = localFont({
  src: [
    {
      path: '../asset/fonts/GmarketSansTTFLight.ttf',
      style: 'normal',
      weight: '300',
    },
    {
      path: '../asset/fonts/GmarketSansTTFMedium.ttf',
      style: 'normal',
      weight: '500',
    },
    {
      path: '../asset/fonts/GmarketSansTTFBold.ttf',
      style: 'normal',
      weight: '700',
    },
  ],
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={clsx(GmarketSans.className)}>
        <ThemeProvider>
          <div
            className={clsx(
              'mx-auto flex flex-col justify-center',
              'max-w-3xl'
            )}
          >
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
